### ISSUE TITLE
[DEVOPS] Setup pipeline for Data

### ISSUE THREAD

**Issue by aronlabr** [unmsmfisi-socialapplication/social_app#10]
considering the choosen technology for backend, create a pipeline which runs:

- unit tests
- linter

**Comment by labrdev** [comment]
Name: CI Data 

- When it is activated: on pull request
- Branch: Main
- Steps or actions performed in the workflow:
- Get the repository code (“Checkout code”)
- We configure the language compiler
- We install the dependencies, if required
- We run the tests (Unit test)

Example of attempt:

```yaml
name: CI Data 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Use the Python version needed

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Data Processing
        run: python data_processing.py  # Replace with Python script

      - name: Run Tests
        run: pytest  # Run your data science tests here

```
