### ISSUE TITLE
[DEVOPS] Add instrument tests in pipeline mobile CI

### ISSUE THREAD

**Issue by serv10** [unmsmfisi-socialapplication/social_app#1136]
Currently, the CI pipeline for the Android project only includes unit tests located within the "Test" folder. However, in the Android Studio environment, there are also instrumentation tests located within the "androidTest" folder. Unlike unit tests, these tests run while a real device or emulator is running since their goal is to simulate the real behavior of the application.

To start instrumentation tests via the command line, run the following command inside the "android" folder:

`./gradlew connectedAndroidTest`

Upon completion of the execution, results will be displayed with important information about the test and whether it was successful. Otherwise, failed tests will be shown, as illustrated in the image below.

![Image](https://github.com/unmsmfisi-socialapplication/social_app/assets/80598612/5e9830f7-b9de-42bc-a256-571e25c60cc4)

The image above shows the result of applying instrumentation tests within the current project, indicating that there are failures that need to be addressed.

**Comment by serv10** [comment]
So, here I show an example of how to apply it within the mobile CI pipeline.

```yaml
- name: Run espresso tests
  uses: reactivecircus/android-emulator-runner@v2
  with:
    api-level: 29
    script: ./gradlew connectedCheck

- name: Upload test report
  uses: actions/upload-artifact@v2
  with:
    name: instrumentation_test_report
    path: android/app/build/reports/androidTests/connected/debug/
```

We must use the `reactivecircus/android-emulator-runner@v2` action to be able to build an emulator within the GitHub Actions environment. I also added the `upload-artifact@v3` action as it is used to save the report as an artifact within Github Actions.
