### ISSUE TITLE
[DEVOPS] Setup pipeline for mobile

### ISSUE THREAD

**Issue by serv10** [unmsmfisi-socialapplication/social_app#18]
considering the choosen technology for mobile, create a pipeline which runs:
- unit tests
- linter

**Comment by serv10** [comment]
The workflow setup process for mobile devices is as follows:

**1. Checkout Code:** This step uses the GitHub action `actions/checkout@v2` to fetch the source code from the repository.
**2. Set Up Kotlin Environment:** This step sets up the environment to use Java 11 using the `actions/setup-java@v2` action. You can configure it with the version you are using of your project.
**3. Build the Application:** It runs the `./gradlew build` command to compile your Kotlin application. This step compiles the project's source code.
**4. Run Test:** It executes the `./gradlew` test command to run unit tests for the application. This verifies the code functions correctly.
**5. Package the Application:** The `./gradlew assembleRelease` command is run to package the application. This may include creating an APK file (in the case of Android applications) or other files necessary for distributing the application.


**Example of attempt:**

```YAML
name: Mobile CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up Kotlin environment
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build App
        run: ./gradlew build

      - name: Test App
        run: ./gradlew test

      - name: Package App
        run: ./gradlew assembleRelease

```
