### ISSUE TITLE
[DEVOPS] Add project configuration file for Data

### ISSUE THREAD

**Issue by aronlabr** [unmsmfisi-socialapplication/social_app#383]
Currently, the data project lacks a centralized and standard way to manage dependencies and project configuration. To address this, we propose the integration of pyproject.toml file along with using poetry as the dependency management tool.

**Proposed Changes**
Add pyproject.toml: Integrate a pyproject.toml file in the project root to manage project configuration, including dependencies, build settings, and other relevant metadata.

Use Poetry for Dependency Management:

- Leverage poetry, a powerful Python package and dependency manager, to handle dependency management in the project.
- Configure pyproject.toml to include necessary dependency information using the tool.poetry.dependencies section.

**Benefits**

- Standardization: Utilizing pyproject.toml aligns with industry best practices for Python projects, promoting consistency and standardization.
- Dependency Management: Poetry simplifies dependency management, providing a clean and efficient way to manage project dependencies and versions.
- Improved Build and Workflow: By having a well-structured pyproject.toml file, it facilitates streamlined builds, dependency resolution, and project maintenance.

**Additional Information**
[Poetry Documentation](https://python-poetry.org/docs/)
[PEP 518 - Specifying Minimum Build System Requirements for Python Projects](https://peps.python.org/pep-0518)
[PEP 621 - Storing project metadata in pyproject.toml](https://peps.python.org/pep-0621)

In this version, the focus is on the technical aspects and the need for feedback from the @beltocas  regarding the proposed changes and their alignment with data management requirements.

**Comment by labrdev** [comment]
Propose implementation
```toml
[tool.poetry]
name = "data"
version = "0.0.0"

# Requirements
[tool.poetry.dependencies]
python = "^3.10"
poetry-core = "1.7.0"
cachecontrol = { version = "^0.13.0", extras = ["filecache"] }

[tool.poetry.groups.lint.dependencies]
ruff = "*"
black = "*"

[tool.poetry.groups.train.dependencies]


[tool.poetry.groups.test.dependencies]


[tool.poetry.groups.build.dependencies]

# only used in github actions
[tool.poetry.group.github-actions]
optional = true
[tool.poetry.group.github-actions.dependencies]
pytest-github-actions-annotate-failures = "^0.1.7"

# Linter configuration using Ruff
[tool.ruff]

# Formatter using Black
[tool.black]
```
