### ISSUE TITLE
[DEVOPS] Implementing Dependabot for Dependency Management

### ISSUE THREAD

**Issue by aronlabr** [unmsmfisi-socialapplication/social_app#581]
Dependabot is a tool that automates dependency updates to ensure our project remains secure and up-to-date. This issue outlines the steps for implementing Dependabot in our project.

**Installation and Setup:**
To get started, follow these steps:
- [X] 1. Install Dependabot by enableling in the repository configurations.
- [X] 2. Inside the `.github` directory, add a configuration file (e.g., `dependabot.yml`).
- [X] 3. Add the label of `dependencies` to group the PRs.
- [X] 4. Test Dependabot updates.
- [ ] 5. Monitor and maintain Dependabot as updates occur.

**Configuration:**
For more information, refer to the official [Dependabot documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically) and [example configurations](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates).

```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
```
**Collaboration**
We invite all team members and contributors to join the discussion, provide feedback, and assist in the implementation of Dependabot.
