### ISSUE TITLE
[DEVOPS] Setup pipeline for backend

### ISSUE THREAD

**Issue by andresrdlc** [unmsmfisi-socialapplication/social_app#7]
considering the choosen technology for backend, create a pipeline which runs:
- unit tests
- linter

**Comment by andresrdlc** [comment]
Name: CI Backend
When it is activated: on pull request
Steps or actions performed in the workflow:

- Get the repository code (“Checkout code”)
- We configure the language compiler
- We install the dependencies, if required
- We run the tests (Unit test)

Example of attempt:
`name: Backend CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test ./path/to/backend

      - name: Run Linter
        run: go vet ./path/to/backend`

**Comment by labrdev** [comment]
Example of attempt:
```YAML
name: Backend CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-22

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Backend
        run: go build -o backend ./path/to/backend

      - name: Run Backend Tests
        run: go test ./path/to/backend
```
