### ISSUE TITLE
[DEVOPS] Setup pipeline for frontend

### ISSUE THREAD

**Issue by pieroHernandezC** [unmsmfisi-socialapplication/social_app#9]
considering the choosen technology for frontend, create a pipeline which runs:
- unit tests
- linter

**Comment by pieroHernandezC** [comment]
On every push to the main branch, it triggers the workflow.
It checks out clean code.
Sets up Node.js and npm.
Installs project dependencies using npm install.
Builds your React app using npm run build.
Runs tests with npm test. Adjust the test command to match the project setup.

```
name: React.js CI

on:
  push:
    branches:
      - main 

jobs:
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: 'node version'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Run tests
      run: npm test
```
